"""
Core implementation of Farey sequences and Farey ranges.

The Farey sequence ``F_n`` is the sequence of completely reduced fractions
between 0 and 1 whose denominators do not exceed ``n``, arranged in order of
increasing size.

A **Farey range** ``FareyRange[x, y, n]`` gives every rational number with
denominator ``<= n`` inside the interval ``[x, y]``, sorted in increasing
order.  Equivalently it is the (sorted) union of all the rational ranges
whose reciprocal steps are the elements of ``FareySequence[n]``.

This is a faithful Python port of the improved Wolfram Language
``FareyRange`` resource function (the version used internally by the
``DanieleGregori/GeneralizedRange`` paclet), computed exactly with the Farey
next-term recurrence rather than by floating-point interval scaling.  The
result is therefore always exact: a list of :class:`fractions.Fraction`.

Author: Daniele Gregori
"""

from fractions import Fraction
from math import ceil, floor, gcd
from typing import List, Union

Number = Union[int, float, Fraction]


class FareyError(Exception):
    """Raised when invalid arguments are passed to farey functions."""


# ---------------------------------------------------------------------------
# Farey sequence
# ---------------------------------------------------------------------------

def farey_sequence(n: int) -> List[Fraction]:
    """
    Generate the Farey sequence of order ``n``.

    The Farey sequence ``F_n`` is the sequence of completely reduced
    fractions between 0 and 1, with denominators less than or equal to
    ``n``, arranged in increasing order.  It is generated in ``O(len(F_n))``
    time by the standard next-term recurrence.

    Parameters
    ----------
    n : int
        The order of the Farey sequence. Must be a positive integer.

    Returns
    -------
    List[Fraction]
        The Farey sequence as a list of :class:`fractions.Fraction`.

    Raises
    ------
    ValueError
        If ``n`` is not a positive integer.

    Examples
    --------
    >>> farey_sequence(1)
    [Fraction(0, 1), Fraction(1, 1)]

    >>> farey_sequence(3)
    [Fraction(0, 1), Fraction(1, 3), Fraction(1, 2), Fraction(2, 3), Fraction(1, 1)]
    """
    if not isinstance(n, int) or isinstance(n, bool) or n < 1:
        raise ValueError(f"Order n must be a positive integer, got {n!r}")

    seq = [Fraction(0, 1)]
    # (p0/q0, p1/q1) start as 0/1 and 1/n, then walk the mediant recurrence.
    p0, q0 = 0, 1
    p1, q1 = 1, n
    seq.append(Fraction(p1, q1))
    while (p1, q1) != (1, 1):
        t = (n + q0) // q1
        p0, q0, p1, q1 = p1, q1, t * p1 - p0, t * q1 - q0
        seq.append(Fraction(p1, q1))
    return seq


# ---------------------------------------------------------------------------
# Farey range — improved FareyRange resource function
# ---------------------------------------------------------------------------
# Transliteration of the improved ``FareyRange`` resource function:
# ``FareyRange[xmin, xmax, n]`` gives the sorted rationals with denominator
# <= n inside ``[xmin, xmax]``, generated by the Farey next-term recurrence
# from a bracketing pair (``_farey_bracket`` / ``_farey_partial``).

def _farey_bracket(r: Fraction, n: int):
    """Consecutive Farey fractions ``fl <= r < fr`` in ``F_n`` (Stern-Brocot)."""
    lo_p, lo_q = 0, 1
    hi_p, hi_q = 1, 1
    while True:
        med_p, med_q = lo_p + hi_p, lo_q + hi_q
        if med_q > n:
            break
        if r < Fraction(med_p, med_q):
            hi_p, hi_q = med_p, med_q
        else:
            lo_p, lo_q = med_p, med_q
    return Fraction(lo_p, lo_q), Fraction(hi_p, hi_q)


def _farey_partial(r0: Fraction, r1: Fraction, n: int) -> List[Fraction]:
    """Farey fractions of order ``n`` within ``[r0, r1] ⊆ [0, 1]``."""
    if r0 == 0 and r1 == 1:
        return farey_sequence(n)
    fb0, fb1 = _farey_bracket(r0, n)
    v, w = fb0.numerator, fb0.denominator
    p, q = fb1.numerator, fb1.denominator
    res: List[Fraction] = []
    while True:
        t = (n + w) // q
        p, v, q, w = t * p - v, p, t * q - w, q
        r = Fraction(p, q)
        if r <= r1:
            res.append(r)
        else:
            break
    if r0 <= fb1 <= r1:
        res.insert(0, fb1)
    if r0 <= fb0 <= r1:
        res.insert(0, fb0)
    return res


def _farey_range_order(xmin: Fraction, xmax: Fraction, den: int) -> List[Fraction]:
    """Ascending rationals with denominator ``<= den`` in ``[xmin, xmax]``.

    ``xmin > xmax`` gives ``[]`` (bounds run against the step).  A degenerate
    ``xmin == xmax`` gives the single point ``[xmin]`` when it lies on the
    order-``den`` Farey grid (denominator ``<= den``), else ``[]`` -- the
    canonical convention shared with algebraic-range's ``_wl_farey_range``.
    """
    if xmin > xmax:
        return []
    if xmin == xmax:
        rep = _farey_bracket(xmin - floor(xmin), den)[0] + floor(xmin)
        return [rep] if rep == xmin else []

    c0 = ceil(xmin)
    f0 = floor(xmin)
    f1 = floor(xmax)

    if f1 - c0 < 0:
        # xmin and xmax fall strictly inside the same unit interval.
        return [f0 + f for f in _farey_partial(xmin - f0, xmax - f0, den)]

    if f0 < c0:
        res = [f0 + f for f in _farey_partial(xmin - f0, Fraction(1), den)]
    else:
        res = [Fraction(f0)]

    unit = farey_sequence(den)[1:]
    for k in range(c0, f1):
        res.extend(k + f for f in unit)
    if xmax > f1:
        res.extend(f1 + f for f in _farey_partial(Fraction(0), xmax - f1, den)[1:])
    return res


# ---------------------------------------------------------------------------
# Step resolution and public wrapper
# ---------------------------------------------------------------------------

def _to_fraction(x: Number, *, context) -> Fraction:
    """Coerce an endpoint to an exact :class:`Fraction`."""
    if isinstance(x, bool):
        raise FareyError(f"{context} must be a real number, got {x!r}")
    if isinstance(x, Fraction):
        return x
    if isinstance(x, int):
        return Fraction(x)
    if isinstance(x, float):
        # Recover the intended rational (e.g. 0.2 -> 1/5) rather than the
        # exact binary value, matching the exact-arithmetic WL behaviour.
        return Fraction(x).limit_denominator(10 ** 9)
    raise FareyError(f"{context} must be a real number, got {x!r}")


def _resolve_step(step: Number) -> tuple:
    """Resolve a ``step`` argument into ``(order, reverse)``.

    Mirrors the WL ``FareyRange`` step conventions:

    - integer ``n > 0``   -> order ``n``, forward
    - integer ``n < 0``   -> order ``|n|``, reversed
    - unit fraction ``1/n``  -> order ``n``, forward
    - unit fraction ``-1/n`` -> order ``n``, reversed
    - zero, or any other rational -> :class:`FareyError`
    """
    frac = _to_fraction(step, context="step")
    if frac == 0:
        raise FareyError("The step parameter 0 is not allowed with FareyRange")

    reverse = frac < 0
    afrac = abs(frac)
    if afrac.denominator == 1:
        return int(afrac), reverse
    if afrac.numerator == 1:
        return afrac.denominator, reverse
    raise FareyError(
        f"The step parameter {step} is not allowed with FareyRange: "
        "it must be a nonzero integer or a unit fraction ±1/n"
    )


def farey_range(
    start: Number,
    end: Number,
    step: Number = 1,
) -> List[Fraction]:
    """
    Generate a Farey range over the interval ``[start, end]``.

    Returns every rational number with denominator ``<= n`` lying inside the
    interval, where ``n`` is the Farey order selected by ``step``.  The result
    is exact: a list of :class:`fractions.Fraction`.

    Parameters
    ----------
    start : int, float, or Fraction
        Left endpoint of the interval.
    end : int, float, or Fraction
        Right endpoint of the interval.
    step : int, float, or Fraction, optional
        Controls the Farey order and direction (default ``1``):

        - positive integer ``n``: Farey order ``n``, ascending;
        - negative integer ``-n``: Farey order ``n``, descending;
        - unit fraction ``1/n``: Farey order ``n``, ascending;
        - unit fraction ``-1/n``: Farey order ``n``, descending.

        Floats are accepted and interpreted as the nearest simple rational
        (e.g. ``0.2`` is ``1/5``).

    Returns
    -------
    List[Fraction]
        Ascending (or descending, for negative ``step``) list of the exact
        rationals with denominator ``<= n`` inside ``[start, end]``.

    Raises
    ------
    FareyError
        If ``step`` is zero, a non-unit fraction, or a non-real value.

    Examples
    --------
    >>> farey_range(0, 1, 3)
    [Fraction(0, 1), Fraction(1, 3), Fraction(1, 2), Fraction(2, 3), Fraction(1, 1)]

    >>> farey_range(0, Fraction(3, 2), 2)
    [Fraction(0, 1), Fraction(1, 2), Fraction(1, 1), Fraction(3, 2)]

    >>> farey_range(1, 0, -3)  # first bound 1, negative step -> descending
    [Fraction(1, 1), Fraction(2, 3), Fraction(1, 2), Fraction(1, 3), Fraction(0, 1)]

    >>> farey_range(0, 1, -3)  # bounds ascend but step is negative -> empty
    []
    """
    order, descending = _resolve_step(step)
    a = _to_fraction(start, context="start")
    b = _to_fraction(end, context="end")

    # Directional, like ``Range[a, b, step]``: the range starts at the first
    # bound and proceeds in the direction of ``step``.  A positive step goes
    # up (non-empty only when a < b); a negative step goes down (non-empty
    # only when a > b).  Reversed bounds -- or a degenerate a == b -- give [].
    if descending:
        result = _farey_range_order(b, a, order)
        result.reverse()
    else:
        result = _farey_range_order(a, b, order)
    return result
